### ISSUE TITLE
ModuleNotFoundError: No module named 'tikhub.__main__'

### ISSUE THREAD

**Issue by cardwords** [TikHubIO/TikHub-API-Python-SDK#15]
如题，无法运行demo，已经安装了tikhub。
Traceback (most recent call last):
  File "/Users/joechow/workspace/spider/python/douyin/test3.py", line 3, in <module>
    from tikhub import TikTokAPI, DouyinAPI
  File "/Users/joechow/Library/Python/3.9/lib/python/site-packages/tikhub/__init__.py", line 10, in <module>
    from tikhub.TikTokAPI import TikTokAPI
  File "/Users/joechow/Library/Python/3.9/lib/python/site-packages/tikhub/TikTokAPI.py", line 1, in <module>
    from tikhub.__main__ import *
ModuleNotFoundError: No module named 'tikhub.__main__'

**Comment by Evil0ctal** [comment]
自述文件未更新，请查看包代码。
